name: File formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check **/*.{md,json,yaml,yml}

      - name: Rzk formatter
        uses: rzk-lang/rzk-action@v1.2.0
        with:
          rzk-version: v0.7.2
          typecheck: false
          check-formatting: true
